### ISSUE TITLE
Nushell configuration

### ISSUE THREAD

**Issue by 101313** [lavafroth/dotfiles#2]
Hey man, I saw you added couple of PRs in relation to completions on nushell and I'd like to take a  look at how you've got completions inside config setup.

Mind sharing the excerpt in a gist maybe?

**Comment by lavafroth** [comment]
I actually rock the default configuration for most of nushell. This eases debugging. The only change I make is adding the carapace completer. Check out https://www.nushell.sh/cookbook/external_completers.html#carapace-completer

**Comment by 101313** [comment]
Thanks for sharing man, keep it up
